# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name': 'a comment',
                'verbose_name_plural': 'comments',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name': 'a feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('photo', models.ImageField(upload_to='main', verbose_name='image')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'a good',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Item'),
        ),
    ]
