# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170812_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='item',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
