# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170812_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('published', models.BooleanField(default=False, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'a comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='published',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='main', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
