# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 16:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170819_1953'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='feedback',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
