# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170824_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
