# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170826_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='item',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
